version: '3.3'

services:
   app:
     build: .
     restart: always
     ports:
        - "3000:3000"
     deploy:
       resources:
         limits:
           cpus: '1'
           memory: 200M
   database:
     image: mongo:latest
     restart: always
